export const API_URL = process.env.EXPO_PUBLIC_API_URL;
export const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL;
export const SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY;

export const STREAM_ENDPOINT = process.env.EXPO_PUBLIC_STREAM_ENDPOINT;
export const STREAM_CLIENT_NAME = process.env.EXPO_PUBLIC_STREAM_CLIENT_NAME;
export const STREAM_CLIENT_VERSION = process.env.EXPO_PUBLIC_STREAM_CLIENT_VERSION;